# Create the MongoDB root user
- name: Create MongoDB root user
  mongodb_user:
    login_port: "{{ login_port }}"
    database: "admin"
    name: "{{ mongodb_root_user }}"
    password: "{{ mongodb_root_password }}"
    roles: "root"
  # no_log: true

- name: Create MongoDB administrative user siteUserAdmin
  mongodb_user:
    login_user: "{{ mongodb_root_user }}"
    login_password: "{{ mongodb_root_password }}"
    login_port: "{{ login_port }}"
    database: "{{ database_name }}"
    name: "{{ mongodb_backup_user }}"
    password: "{{ mongodb_backup_password }}"
    roles:
      - { db: "{{ database_name }}", role: "readWrite" }
      - { db: "admin", role: "backup" }
  no_log: true

